### ISSUE TITLE
Einrücken in Blockzitat funktioniert nicht

### ISSUE THREAD

**Issue by marcgauch** [giodi/Vorlage-FHGR#14]
## Situation

Der Vorlagetext in `content/02_textteil/kapitel1.tex` beinhaltet folgendes:
```latex
\begin{quote}
Blockzitate sind wörtliche Zitate von 40 Wörtern oder mehr; sie werden als eigener Absatz ohne Anführungszeichen angeführt.
Ein Blockzitat beginnt stets in einer neuen Zeile, wird zur Gänze (also jede Zeile) 1,3 cm oder fünf Leerschritte eingerückt und mit zweizeiligem Abstand geschrieben. Absätze innerhalb eines Blockzitates werden vom neuen Rand des Blockzitates eingerückt. Blockzitate werden nicht in Anführungszeichen gesetzt, darin aufscheinende Zitate werden in doppelten Anführungszeichen wiedergegeben. Die Quellenangabe am Ende eines Blockzitates steht nach dem letzten schließenden Punkt des Zitates in Klammern gesetzt, danach folgt kein weiterer Punkt.\\
\parencite[S. 111]{psychologie_richtlinien_2016}
\end{quote}
```

Dieses Beispiel enthält nur einen Paragrafen.

Fügt man aber hinter dem ersten Satz ein:
```latex
\\
```
,

```latex
\newline
```
oder eine Leerzeile ein. So wird der nachfolgende Satz nicht eingerückt.
Zusätzlich unterscheiden sich die erstgenannten Optionen von der Leerzeile. Im PDF ist mit der Leerzeile der Abstand grösser.

## Was gemacht werden muss
- [ ] Quelle für den Style finden
- [x] Einrücken anpassen
- [x] Beispiel um einen Abschnitt erweitern

**Comment by giodi** [comment]
Im Commit https://github.com/giodi/Vorlage-FHGR/commit/c85c3186574fa73466fd5f8d43c3d8eadb6627a1 habe ich Verbesserungen vorgenommen.

Achtung: `\newline` und `\\` erzeugen einen Umbruch, `\par` oder eine Leerzeile dagegen einen neuen Absatz (welcher jetzt immer mit 1,3 cm eingerückt wird).
