### ISSUE TITLE
Seitennummerierung in Selbständigkeitserklärung 

### ISSUE THREAD

**Issue by marcgauch** [giodi/Vorlage-FHGR#9]
Gemäss *Leitfaden zum wissenschaftlichen Arbeiten an der FH Graubünden.pdf* V01.00 Tabelle Seite 13 hat die Selbständigkeitserklärung keine Seitennummer.

![image](https://github.com/giodi/Vorlage-FHGR/assets/34353267/3c1e584a-af3c-4815-9594-d5bd503b3daa)

**Comment by giodi** [comment]
In https://github.com/giodi/Vorlage-FHGR/commit/127f58f46b8090911b7a0f6820a8b2990d63c2c7 gelöst.
